#!/bin/bash

set -xe

(cd ~/fieldkit/testing && make)
scp ~/fieldkit/testing/build/linux-arm/fk-data-tool fknatpi:

rsync -zvua --progress ../../conservify/arduino-logging gitdeps
rsync -zvua --progress ../../fieldkit/lwstreams gitdeps
rsync -zvua --delete --exclude archive --exclude build ../simple-lora-comms fknatpi: && ssh -tt fknatpi "cd simple-lora-comms && make"
