#!/bin/bash

HOST=$1

if [[ -z $HOST ]]; then
    exit 2
fi

set -xe

(cd ~/fieldkit/testing && make)
scp ~/fieldkit/testing/build/linux-arm/fk-data-tool $HOST:

rsync -zvua --progress ../../conservify/arduino-logging gitdeps
rsync -zvua --progress ../../fieldkit/lwstreams gitdeps
rsync -zvua --progress ../../conservify/cmake $HOST:
rsync -zvua --delete --exclude archive --exclude build ../simple-lora-comms $HOST: && ssh -tt $HOST "cd simple-lora-comms && CMAKE_MODULE_PATH=~/cmake make"
