#!/bin/bash

set -xe

(cd ~/fieldkit/testing && make)
scp ~/fieldkit/testing/build/linux-arm/fk-data-tool fknatpi:

rsync -zvua --progress ../../conservify/arduino-logging gitdeps
rsync -zvua --progress ../../fieldkit/lwstreams gitdeps
rsync -zvua --delete --exclude archive --exclude build ../simple-lora-comms fknatpi: && ssh -tt fknatpi "cd simple-lora-comms && make && build/pi/lora-pi-test --command '~/fk-data-tool --post-stream --host api.fkdev.org --scheme https' --archive '/root/archive'"
