#!/bin/bash

set -xe

rsync -zvua --progress ../../fieldkit/lwstreams gitdeps
rsync -zvua --delete --exclude build ../lora-pi-mcu-test fknatpi: && ssh -tt fknatpi "cd lora-pi-mcu-test && make && build/pi/lora-pi-test"
