/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_FK_RADIO_FK_RADIO_PB_H_INCLUDED
#define PB_FK_RADIO_FK_RADIO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _fk_radio_PacketKind {
    fk_radio_PacketKind_ACK = 0,
    fk_radio_PacketKind_NACK = 1,
    fk_radio_PacketKind_PING = 2,
    fk_radio_PacketKind_PONG = 3,
    fk_radio_PacketKind_PREPARE = 4,
    fk_radio_PacketKind_DATA = 5
} fk_radio_PacketKind;
#define _fk_radio_PacketKind_MIN fk_radio_PacketKind_ACK
#define _fk_radio_PacketKind_MAX fk_radio_PacketKind_DATA
#define _fk_radio_PacketKind_ARRAYSIZE ((fk_radio_PacketKind)(fk_radio_PacketKind_DATA+1))

/* Struct definitions */
typedef struct _fk_radio_RadioPacket {
    fk_radio_PacketKind kind;
    pb_callback_t nodeId;
    int32_t address;
    int32_t size;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:fk_radio_RadioPacket) */
} fk_radio_RadioPacket;


/* Initializer values for message structs */
#define fk_radio_RadioPacket_init_default        {_fk_radio_PacketKind_MIN, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define fk_radio_RadioPacket_init_zero           {_fk_radio_PacketKind_MIN, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define fk_radio_RadioPacket_kind_tag            1
#define fk_radio_RadioPacket_nodeId_tag          2
#define fk_radio_RadioPacket_address_tag         3
#define fk_radio_RadioPacket_size_tag            4
#define fk_radio_RadioPacket_data_tag            5

/* Struct field encoding specification for nanopb */
#define fk_radio_RadioPacket_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UENUM, kind, 1) \
X(a, CALLBACK, SINGULAR, BYTES, nodeId, 2) \
X(a, STATIC, SINGULAR, INT32, address, 3) \
X(a, STATIC, SINGULAR, INT32, size, 4) \
X(a, CALLBACK, SINGULAR, BYTES, data, 5)
#define fk_radio_RadioPacket_CALLBACK pb_default_field_callback
#define fk_radio_RadioPacket_DEFAULT NULL

extern const pb_msgdesc_t fk_radio_RadioPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define fk_radio_RadioPacket_fields &fk_radio_RadioPacket_msg

/* Maximum encoded size of messages (where known) */
/* fk_radio_RadioPacket_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
